#!/usr/bin/env bash
#
# Regenerate all Go and Python types from contracts/.
#
#   scripts/contracts-generate.sh              # write into gen/
#   scripts/contracts-generate.sh /tmp/out     # write elsewhere (used by verify)
#
# Output must be byte-for-byte deterministic, because contracts-verify.sh
# diffs a fresh generation against the committed tree. Anything that varies
# between runs — a timestamp, a map iteration order, an absolute path in a
# header — turns the drift gate into a coin flip and it gets disabled within a
# week. Hence --disable-timestamp below, and hence the generators run against a
# staged copy at a fixed relative path rather than against $PWD.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="${1:-$ROOT/gen}"
TOOLS="$ROOT/.tools/bin"

# Pinned exactly. A generator minor bump that reformats output would fail the
# drift check for no semantic reason, and debugging that is a bad afternoon.
OAPI_CODEGEN_VERSION="v2.4.1"
GO_JSONSCHEMA_VERSION="v0.24.1"
DATAMODEL_CG_VERSION="0.28.5"

# datamodel-code-generator 0.28.5 cannot run under Python 3.14 — it maps
# sys.version_info onto a closed PythonVersion enum and raises on anything it
# does not know. Pin the interpreter it runs under, independently of whatever
# python3 happens to be on PATH.
DATAMODEL_CG_PYTHON="3.12"

blue()  { printf '\033[0;36m==> %s\033[0m\n' "$*"; }
green() { printf '  \033[0;32m%s\033[0m\n' "$*"; }

command -v go >/dev/null || { echo "error: go is required" >&2; exit 1; }
command -v uv >/dev/null || { echo "error: uv is required" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------

mkdir -p "$TOOLS"
[[ -x "$TOOLS/oapi-codegen" ]] || {
  blue "installing oapi-codegen $OAPI_CODEGEN_VERSION"
  GOBIN="$TOOLS" go install "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@$OAPI_CODEGEN_VERSION"
}
[[ -x "$TOOLS/go-jsonschema" ]] || {
  blue "installing go-jsonschema $GO_JSONSCHEMA_VERSION"
  GOBIN="$TOOLS" go install "github.com/atombender/go-jsonschema@$GO_JSONSCHEMA_VERSION"
}

# ---------------------------------------------------------------------------
# Go — event structs from JSON Schema
# ---------------------------------------------------------------------------
#
# go-jsonschema resolves $ref as a FILESYSTEM PATH. Our schemas use relative
# refs precisely so this works (see contracts/README.md), but it still needs to
# be told which $id maps to which output file and package, because it will not
# infer either from the directory layout.

blue "go-jsonschema -> $OUT/go/events"
rm -rf "$OUT/go/events"
mkdir -p "$OUT/go/events"

declare -a GJS_ARGS=() GJS_FILES=()
while IFS=$'\t' read -r file id; do
  slug="$(basename "$file" .schema.json | tr '.' '_')"
  GJS_ARGS+=( "--schema-package=${id}=events" )
  GJS_ARGS+=( "--schema-output=${id}=${OUT}/go/events/${slug}.gen.go" )
  GJS_FILES+=( "$file" )
done < <(
  for f in contracts/common/*.schema.json contracts/events/*.schema.json; do
    printf '%s\t%s\n' "$f" "$(python3 -c "import json;print(json.load(open('$f'))['\$id'])")"
  done
)

"$TOOLS/go-jsonschema" \
  --only-models \
  --struct-name-from-title \
  --package events \
  "${GJS_ARGS[@]}" "${GJS_FILES[@]}"

green "$(ls -1 "$OUT/go/events" | wc -l | tr -d ' ') files"

# --- Fix a real defect in the generated Go -------------------------------
#
# For a `"format": "date-time"` field, go-jsonschema emits a DEFINED type:
#
#     type OccurredAt time.Time
#
# not an alias. In Go, a defined type does not inherit the methods of its
# underlying type, so OccurredAt has no MarshalJSON/UnmarshalJSON and every
# timestamp in every event silently fails to decode:
#
#     json: cannot unmarshal string into Go struct field ... of type events.OccurredAt
#
# This is exactly the shape of bug this project's test strategy exists to
# catch: the code compiles, `go vet` is clean, the types look right, and it is
# broken at runtime on the very first message. It was found by the round-trip
# test in gen/go/contracttest, not by reading the output.
#
# The fix is emitted here rather than hand-written into gen/go/events, because
# that directory is deleted on every generation. Types are discovered by
# scanning the output, so a new timestamp field in a future schema is covered
# automatically instead of failing the same way a year from now.

blue "emitting JSON methods for generated time types"
TIME_TYPES=$(grep -h '^type .* time\.Time$' "$OUT"/go/events/*.gen.go \
             | awk '{print $2}' | sort -u)

{
  cat <<'HDR'
// Code generated by scripts/contracts-generate.sh. DO NOT EDIT.
//
// go-jsonschema emits `type X time.Time` for date-time fields — a defined
// type, not an alias — so X does not inherit time.Time's JSON methods and
// cannot round-trip. These implementations restore RFC 3339 marshalling.
//
// Regenerated from the type list found in the generated output, so a new
// timestamp field in a future schema is covered without touching this file.

package events

import (
	"fmt"
	"time"
)
HDR
  for t in $TIME_TYPES; do
    cat <<EOF

// MarshalJSON renders $t as an RFC 3339 timestamp in UTC.
func (t $t) MarshalJSON() ([]byte, error) {
	return []byte(\`"\` + time.Time(t).UTC().Format(time.RFC3339Nano) + \`"\`), nil
}

// UnmarshalJSON parses an RFC 3339 timestamp into $t.
func (t *$t) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("$t must be an RFC 3339 string: %w", err)
	}
	parsed, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return fmt.Errorf("$t %q is not RFC 3339: %w", s, err)
	}
	*t = $t(parsed)
	return nil
}

// Time returns the underlying time.Time.
func (t $t) Time() time.Time { return time.Time(t) }
EOF
  done
} > "$OUT/go/events/time_json.gen.go"

# json is used by the Unmarshal implementations above.
sed -i.bak 's|^import (|import (\n\t"encoding/json"|' "$OUT/go/events/time_json.gen.go"
rm -f "$OUT/go/events/time_json.gen.go.bak"
gofmt -w "$OUT/go/events/time_json.gen.go"
green "$(echo "$TIME_TYPES" | wc -w | tr -d ' ') time types: $(echo $TIME_TYPES | tr '\n' ' ')"

# ---------------------------------------------------------------------------
# Go — OpenAPI types and strict chi server
# ---------------------------------------------------------------------------

blue "oapi-codegen -> $OUT/go/taskingapi"
rm -rf "$OUT/go/taskingapi"
mkdir -p "$OUT/go/taskingapi"
"$TOOLS/oapi-codegen" \
  --config contracts/codegen/oapi-codegen.tasking-api.yaml \
  -o "$OUT/go/taskingapi/taskingapi.gen.go" \
  contracts/openapi/tasking-api.v1.yaml
green "$(wc -l < "$OUT/go/taskingapi/taskingapi.gen.go" | tr -d ' ') lines"

# ---------------------------------------------------------------------------
# Python — Pydantic v2 models from the same schemas
# ---------------------------------------------------------------------------
#
# Staged into a temp tree containing only common/ and events/. Pointing the
# generator at contracts/ directly would also sweep in openapi/, examples/, and
# codegen/, and the generated package would carry files nobody asked for.

blue "datamodel-code-generator -> $OUT/python/overpass_contracts"

# The staging directory's BASENAME ends up inside the generated file headers
# (`# filename: <basename>`), so a random mktemp name makes the output
# non-deterministic and the drift gate fails on every run for no reason. The
# parent is still a fresh temp dir for isolation; only the leaf name is fixed,
# and it is fixed to "contracts" so the header says something true.
STAGE_PARENT="$(mktemp -d)"
STAGE="$STAGE_PARENT/contracts"
trap 'rm -rf "$STAGE_PARENT"' EXIT
mkdir -p "$STAGE"
cp -R contracts/common contracts/events "$STAGE/"

rm -rf "$OUT/python/overpass_contracts"
mkdir -p "$OUT/python/overpass_contracts"

uvx --quiet --python "$DATAMODEL_CG_PYTHON" \
    --from "datamodel-code-generator==$DATAMODEL_CG_VERSION" datamodel-codegen \
  --input "$STAGE" \
  --input-file-type jsonschema \
  --output "$OUT/python/overpass_contracts" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.12 \
  --use-annotated \
  --use-standard-collections \
  --use-union-operator \
  --enum-field-as-literal one \
  --use-schema-description \
  --use-field-description \
  --snake-case-field \
  --disable-timestamp

# datamodel-codegen writes common/__init__.py and events/__init__.py but not a
# root one, and the generated modules use relative imports (`from ..common
# import ...`). Without this the package cannot be imported at all.
cat > "$OUT/python/overpass_contracts/__init__.py" <<'PY'
"""Generated Pydantic models for the Overpass event contracts.

DO NOT EDIT. Produced from contracts/ by `make contracts-generate`.
`make contracts-verify` fails CI if this tree differs from a fresh generation.
"""
PY

green "$(find "$OUT/python/overpass_contracts" -name '*.py' | wc -l | tr -d ' ') modules"

blue "done"
